# Generated by Django 5.0.6 on 2024-07-17 15:08

import builtins
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_type', models.CharField(choices=[('Odd', 'Odd Days'), ('Even', 'Even Days'), ('Any', 'Any Day')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='timeslot',
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Orar.instructor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='day_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Orar.daytype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='hours',
            field=models.ForeignKey(default=2000, on_delete=django.db.models.deletion.CASCADE, to='Orar.hours'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Timeslot',
        ),
    ]
