# Generated by Django 5.0.6 on 2024-07-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0003_alter_timetable_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytype',
            name='day_type',
            field=models.CharField(choices=[('Odd', 'Odd Days'), ('Even', 'Even Days'), ('Any', 'Any Day')], max_length=4),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9),
        ),
    ]
