# Generated by Django 5.0.6 on 2024-07-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0004_alter_daytype_day_type_alter_timetable_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='students',
            new_name='group',
        ),
    ]
