# Generated by Django 5.0.6 on 2024-07-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0006_alter_timetable_day_type_delete_daytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='hours',
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(default='21:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(default='22:00:00'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Hours',
        ),
    ]
