# Generated by Django 5.0.6 on 2024-07-17 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0007_remove_timetable_hours_timetable_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timetable',
            name='hours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Orar.hours'),
            preserve_default=False,
        ),
    ]
