# Generated by Django 5.0.6 on 2024-07-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0008_hours_remove_timetable_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='group',
            new_name='year',
        ),
    ]
