# Generated by Django 5.0.6 on 2024-07-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0009_rename_group_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='course_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Laboratory', 'Laboratory'), ('Seminar', 'Seminar')], default='Lecture', max_length=10),
            preserve_default=False,
        ),
    ]
