# Generated by Django 5.0.6 on 2024-07-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0010_timetable_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='course_type',
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Laboratory', 'Laboratory'), ('Seminar', 'Seminar')], default='Lecture', max_length=10),
            preserve_default=False,
        ),
    ]
