# Generated by Django 5.0.6 on 2024-07-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0011_remove_timetable_course_type_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday (IFR)', 'Saturday'), ('Sunday (IFR)', 'Sunday')], max_length=14),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day_type',
            field=models.CharField(choices=[('Odd', 'Odd Weeks'), ('Even', 'Even Weeks'), ('Any', 'Any Weeks')], max_length=4),
        ),
    ]
