# Generated by Django 5.0.6 on 2024-08-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0013_alter_timetable_day'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hours',
            new_name='Hour',
        ),
    ]
