# Generated by Django 5.0.6 on 2024-08-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0014_rename_hours_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
        migrations.AddField(
            model_name='timetable',
            name='course_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Laboratory', 'Laboratory'), ('Seminar', 'Seminar')], default='among us', max_length=10),
            preserve_default=False,
        ),
    ]
