# Generated by Django 5.0.6 on 2024-08-04 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0015_remove_course_course_type_timetable_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='instructor',
        ),
    ]
