# Generated by Django 5.0.6 on 2024-08-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0016_remove_timetable_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day_type',
            field=models.CharField(choices=[('Odd', 'Odd Weeks'), ('Even', 'Even Weeks'), ('Any', 'Any Week')], max_length=4),
        ),
    ]
