# Generated by Django 5.0.6 on 2024-08-04 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0017_alter_timetable_day_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.AddField(
            model_name='timetable',
            name='instructor',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='Orar.instructor'),
            preserve_default=False,
        ),
    ]
