# Generated by Django 5.0.6 on 2024-08-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0018_remove_course_instructor_timetable_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day_type',
            field=models.CharField(choices=[('Odd Weeks', 'Odd Weeks'), ('Even Weeks', 'Even Weeks'), ('Any Week', 'Any Week')], max_length=10),
        ),
    ]
