# Generated by Django 5.0.6 on 2024-08-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0019_alter_timetable_day_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='day_type',
            new_name='week_type',
        ),
    ]
