# Generated by Django 5.0.6 on 2024-08-19 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0021_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Orar.group'),
            preserve_default=False,
        ),
    ]
