# Generated by Django 5.0.6 on 2024-08-30 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0022_timetable_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='class_type',
            field=models.CharField(choices=[('Single Class', 'Single Class'), ('Dual Class', 'Dual Class'), ('Different Subgroups', 'Different Subgroups')], default='Single Class', max_length=20),
        ),
        migrations.AddField(
            model_name='timetable',
            name='second_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_course', to='Orar.course'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='second_course_type',
            field=models.CharField(blank=True, choices=[('Lecture', 'Lecture'), ('Laboratory', 'Laboratory'), ('Seminar', 'Seminar')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='second_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_instructor', to='Orar.instructor'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='second_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_room', to='Orar.room'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='second_week_type',
            field=models.CharField(blank=True, choices=[('Odd Weeks', 'Odd Weeks'), ('Even Weeks', 'Even Weeks'), ('Any Week', 'Any Week')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orar.course'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='course_type',
            field=models.CharField(blank=True, choices=[('Lecture', 'Lecture'), ('Laboratory', 'Laboratory'), ('Seminar', 'Seminar')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orar.instructor'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orar.room'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='week_type',
            field=models.CharField(blank=True, choices=[('Odd Weeks', 'Odd Weeks'), ('Even Weeks', 'Even Weeks'), ('Any Week', 'Any Week')], max_length=10, null=True),
        ),
    ]
