# Generated by Django 5.0.6 on 2024-08-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orar', '0023_timetable_class_type_timetable_second_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='assigned_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
